version: '3'
services:
  httpd:
    build: ./apache
    ports:
     - "8080:80"
    environment:
      FPM_HOST: php:9000
    volumes: 
      - ./app/:/var/www/html/
    links:
      - php
  php:    
    build: ./php
    volumes: 
      - ./app/:/var/www/html/
