FROM ubuntu

RUN apt-get update && apt-get install -y apache2 \
	vim

RUN a2enmod proxy_fcgi

ADD ./conf/app.conf /etc/apache2/sites-available/
RUN a2ensite app

# Enabling mod_rewrite
RUN a2enmod rewrite

# COPY 000-default.conf /etc/apache2/sites-available
# COPY app.conf /etc/apache2/sites-available
# RUN service apache2 restart
EXPOSE 80

# On donne les droits au user www-data pour les sources dans le container
# Sans ça, on a des "permission denied" pour certains fichiers/répertoires
# RUN adduser --disabled-password florian
# RUN usermod -u 1000 florian
# RUN chown -R florian:florian /var/www
RUN chmod -R 771 /var/www

# On démarre le server apache
CMD /usr/sbin/apache2ctl -D FOREGROUND